### ISSUE TITLE
.gopmfile res节

### ISSUE THREAD

**Issue by shionryuu** [gpmgo/docs#2]
docs/zh-CN/gopmfile.md res节没有说明

**Comment by zhangbc** [comment]
报错：
☁  demo  vi .gopmfile
☁  demo  gopm get
[GOPM] 10-12 00:21:10 [ERROR] github.com/astaxie/beego: fail to make request: Get "https://gopm.io/api/v1/download?pkgname=github.com/astaxie/beego&revision=v0.9.0": dial tcp: lookup gopm.io: no such host

gopm.io 已经不存在啦！！！
